trigger:
  - master

pool:
  vmImage: 'Ubuntu-16.04'
  DOCKER_BUILDKIT: 1

variables:
  DOCKER_BUILDKIT: 1

steps:
  - task: Gradle@2
    displayName: Gradle build
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: assemble
#  - task: CopyFiles@2
#    inputs:
#      contents: '**/*.jar'
#      targetFolder: '$(build.artifactStagingDirectory)'
#  - task: PublishBuildArtifacts@1
  - task: Docker@2
    displayName: Build and push into Container registry
    inputs:
      repository: demo/devopsdemocontainer
      command: build
      dockerfile: Dockerfile
      containerRegistry: azuresubscription1cr
      tags: |
        $(Build.BuildId)
        latest
