trigger:
  - master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'azure-devops-sample-docker'

steps:
  - task: Gradle@2
    displayName: Gradle build
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: build
  - task: Docker@2
    displayName: Build azure-devops-sample docker image
    inputs:
      repository: $(imageName)
      command: build
      Dockerfile: Dockerfile