trigger:
  - master

pool:
  vmImage: 'Ubuntu-16.04'
  DOCKER_BUILDKIT: 1

variables:
  imageName: 'azuredevopssample'
  DOCKER_BUILDKIT: 1

steps:
  - task: Gradle@2
    displayName: Gradle build
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: build
  - task: Docker@2
    displayName: Build azure-devops-sample docker image
    inputs:
      repository: demo/azuredevopssample
      command: buildAndPush
      dockerfile: Dockerfile
      containerRegistry: demoregistry945
      tags: |
        $(Build.BuildId)
        latest
      